import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Page, SearchBar, SectionHeading, DriveCard, ExperienceCard, StatusBadge, CompanyLogo } from "@/components/campus/shared";
import { drives, experiences } from "@/data/campus";

export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title:"Dashboard — Campus Prep"},{name:"description",content:"Your personalized campus placement overview and next preparation steps."},{property:"og:title",content:"Student Dashboard — Campus Prep"},{property:"og:description",content:"Your current drives, recent experiences, and preparation plan."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: Dashboard });
function Dashboard(){return <Page><div className="mb-8"><p className="eyebrow">Monday, 21 September</p><h1 className="page-title mt-3">Good morning, Aman.</h1><p className="mt-2 text-sm text-muted-foreground">B.Tech Computer Science · Class of 2027<br className="sm:hidden"/> <span className="hidden sm:inline">·</span> XYZ University · Placement Cycle 2026–27</p></div><SearchBar/>
<section className="mt-12"><SectionHeading label="Open for you" description="Companies currently relevant to your program." action={<Link to="/drives" className="hidden items-center gap-1 text-sm font-medium text-primary sm:flex">All drives <ArrowRight className="size-4"/></Link>}/><div className="grid gap-4 lg:grid-cols-3">{drives.slice(0,3).map(d=><DriveCard key={d.company} drive={d}/>)}</div></section>
<div className="mt-14 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><section><SectionHeading label="Your placement journey"/>{([{company:"Microsoft",status:"Participated",detail:"Experience submitted"},{company:"Amazon",status:"Participated",detail:"Experience pending"},{company:"Google",status:"Saved",detail:"Saved for later"}] as const).map(item=><div key={item.company} className="flex items-center justify-between border-b border-border py-4"><div className="flex items-center gap-3"><CompanyLogo name={item.company} size="sm"/><div><p className="text-sm font-medium">{item.company}</p><p className="text-xs text-muted-foreground">{item.detail}</p></div></div><StatusBadge status={item.status}/></div>)}</section><section><SectionHeading label="Continue preparing"/><div className="content-card p-6"><div className="flex items-center gap-3"><CompanyLogo name="Microsoft"/><div><h3 className="card-title">Microsoft</h3><p className="text-sm text-muted-foreground">Software Engineer</p></div></div><div className="mt-7 flex items-center justify-between text-sm"><span>Preparation progress</span><strong>72%</strong></div><Progress value={72} className="mt-3"/><div className="mt-6 flex flex-col justify-between gap-4 border-t border-border pt-5 sm:flex-row sm:items-center"><div><p className="eyebrow">Next</p><p className="mt-1 text-sm font-medium">Revise Binary Trees</p></div><Button asChild><Link to="/preparation">Continue Preparation <ArrowRight/></Link></Button></div></div></section></div>
<section className="mt-14"><SectionHeading label="Recent experiences"/><div className="grid gap-x-10 lg:grid-cols-3">{experiences.slice(0,3).map(e=><ExperienceCard key={e.company} experience={e}/>)}</div></section></Page>}