import { createFileRoute } from "@tanstack/react-router";
import { Check, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Page, CompanyLogo, SaveButton, Metric, SectionHeading, ExperienceCard, QuestionRow } from "@/components/campus/shared";
import { experiences, questions, resources } from "@/data/campus";
export const Route=createFileRoute("/drives/microsoft-2026")({head:()=>({meta:[{title:"Microsoft Software Engineer Drive — Campus Prep"},{name:"description",content:"Eligibility, hiring process, student experiences, and preparation for Microsoft’s 2026–27 campus drive."},{property:"og:title",content:"Microsoft Campus Drive — Campus Prep"},{property:"og:description",content:"Reported process, questions, and student experiences for Microsoft Software Engineer."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:DriveDetail});
function DriveDetail(){const timeline=[["Online Assessment","3 coding questions"],["Technical Interview","DSA · OOP · Projects"],["Technical Interview","DBMS · Graphs"],["HR","Behavioral"]];return <Page><header className="flex flex-col justify-between gap-6 border-b border-border pb-8 md:flex-row md:items-end"><div className="flex items-start gap-4"><CompanyLogo name="Microsoft" size="lg"/><div><p className="eyebrow">Microsoft</p><h1 className="page-title mt-2">Software Engineer</h1><p className="mt-2 text-sm text-muted-foreground">Campus Drive · 2026–27 &nbsp; <Badge variant="secondary">B.Tech</Badge></p></div></div><div className="flex gap-2"><SaveButton/><Button><Check/> I Participated</Button></div></header>
<section className="grid divide-y divide-border border-b border-border sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4"><Metric label="Eligibility" value="7+ CGPA" detail="No active backlogs"/><Metric label="Deadline" value="25 Sep 2026" detail="11:59 PM"/><Metric label="Experiences" value="21 students" detail="8 selected"/><Metric label="Questions" value="58 reported" detail="Across 4 rounds"/></section>
<div className="mt-14 grid gap-14 lg:grid-cols-[1.25fr_.75fr]"><div><section><SectionHeading label="Hiring process" title="Reported Hiring Process" description="Synthesized from 21 student submissions."/><div className="mt-8">{timeline.map(([t,d],i)=><div key={`${t}-${i}`} className="relative flex gap-5 pb-8 last:pb-0"><div className="relative z-10 grid size-9 shrink-0 place-items-center rounded-full border border-border bg-surface text-xs font-semibold text-primary">{String(i+1).padStart(2,"0")}</div>{i<timeline.length-1&&<span className="absolute left-[17px] top-9 h-[calc(100%-36px)] w-px bg-border"/>}<div className="pt-1"><h3 className="font-semibold">{t}</h3><p className="mt-1 text-sm text-muted-foreground">{d}</p></div></div>)}</div></section><section className="mt-14"><SectionHeading label="Previous student experiences"/>{experiences.slice(0,2).map(e=><ExperienceCard key={e.company} experience={{...e,company:"Microsoft",role:"Software Engineer"}}/>)}</section></div>
<aside className="space-y-12"><section><SectionHeading label="Frequently reported questions"/>{questions.slice(0,4).map(q=><QuestionRow key={q.title} {...q}/>)}</section><section><SectionHeading label="Preparation resources"/>{resources.slice(0,3).map(r=><div key={r.title} className="border-b border-border py-4"><p className="text-sm font-medium">{r.title}</p><p className="mt-1 text-xs text-muted-foreground">{r.kind} · {r.detail}</p></div>)}</section><section><SectionHeading label="Seniors from your college"/>{["Nisha K.","Rahul S.","Priya M."].map((n,i)=><div key={n} className="flex items-center gap-3 border-b border-border py-3"><span className="avatar-control">{n[0]}{n.split(" ")[1][0]}</span><div><p className="text-sm font-medium">{n}</p><p className="text-xs text-muted-foreground">B.Tech · Class of {2026-i}</p></div><Users className="ml-auto size-4 text-muted-foreground"/></div>)}</section></aside></div></Page>}