/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as PreparationRouteImport } from './routes/preparation'
import { Route as DrivesMicrosoft2026RouteImport } from './routes/drives.microsoft-2026'
import { Route as ExperiencesMicrosoftExampleRouteImport } from './routes/experiences.microsoft-example'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationRoute = PreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesMicrosoft2026Route = DrivesMicrosoft2026RouteImport.update({
  id: '/microsoft-2026',
  path: '/microsoft-2026',
  getParentRoute: () => DrivesRoute,
} as any)
const ExperiencesMicrosoftExampleRoute =
  ExperiencesMicrosoftExampleRouteImport.update({
    id: '/microsoft-example',
    path: '/microsoft-example',
    getParentRoute: () => ExperiencesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/preparation': typeof PreparationRoute
  '/drives/microsoft-2026': typeof DrivesMicrosoft2026Route
  '/experiences/microsoft-example': typeof ExperiencesMicrosoftExampleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/preparation': typeof PreparationRoute
  '/drives/microsoft-2026': typeof DrivesMicrosoft2026Route
  '/experiences/microsoft-example': typeof ExperiencesMicrosoftExampleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRouteWithChildren
  '/experiences': typeof ExperiencesRouteWithChildren
  '/preparation': typeof PreparationRoute
  '/drives/microsoft-2026': typeof DrivesMicrosoft2026Route
  '/experiences/microsoft-example': typeof ExperiencesMicrosoftExampleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/dashboard'
    | '/drives'
    | '/experiences'
    | '/preparation'
    | '/drives/microsoft-2026'
    | '/experiences/microsoft-example'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/dashboard'
    | '/drives'
    | '/experiences'
    | '/preparation'
    | '/drives/microsoft-2026'
    | '/experiences/microsoft-example'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/dashboard'
    | '/drives'
    | '/experiences'
    | '/preparation'
    | '/drives/microsoft-2026'
    | '/experiences/microsoft-example'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  DashboardRoute: typeof DashboardRoute
  DrivesRoute: typeof DrivesRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  PreparationRoute: typeof PreparationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation': {
      id: '/preparation'
      path: '/preparation'
      fullPath: '/preparation'
      preLoaderRoute: typeof PreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives/microsoft-2026': {
      id: '/drives/microsoft-2026'
      path: '/microsoft-2026'
      fullPath: '/drives/microsoft-2026'
      preLoaderRoute: typeof DrivesMicrosoft2026RouteImport
      parentRoute: typeof DrivesRoute
    }
    '/experiences/microsoft-example': {
      id: '/experiences/microsoft-example'
      path: '/microsoft-example'
      fullPath: '/experiences/microsoft-example'
      preLoaderRoute: typeof ExperiencesMicrosoftExampleRouteImport
      parentRoute: typeof ExperiencesRoute
    }
  }
}

interface DrivesRouteChildren {
  DrivesMicrosoft2026Route: typeof DrivesMicrosoft2026Route
}

const DrivesRouteChildren: DrivesRouteChildren = {
  DrivesMicrosoft2026Route: DrivesMicrosoft2026Route,
}

const DrivesRouteWithChildren =
  DrivesRoute._addFileChildren(DrivesRouteChildren)

interface ExperiencesRouteChildren {
  ExperiencesMicrosoftExampleRoute: typeof ExperiencesMicrosoftExampleRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesMicrosoftExampleRoute: ExperiencesMicrosoftExampleRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  DashboardRoute: DashboardRoute,
  DrivesRoute: DrivesRouteWithChildren,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  PreparationRoute: PreparationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
